In [1]:
import numpy as np

## Matrix-Vector Addition

In [2]:
X = np.array([
    [1, 2, 3]
])

In [3]:
X

array([[1, 2, 3]])

In [4]:
b = np.array([10, 20, 30])

In [5]:
b

array([10, 20, 30])

In [6]:
X + b

array([[11, 22, 33]])

In [7]:
X2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [8]:
X2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
X2 + b

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

## Matrix-Matrix Multiplication

In [10]:
X = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

In [11]:
X

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [12]:
W = np.array([
    [10.0, 20.0],
    [30.0, 40.0],
    [50.0, 60.0]
])

In [13]:
W

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.]])

In [14]:
np.dot(X, W)

array([[ 220.,  280.],
       [ 490.,  640.]])

In [15]:
np.sum(np.dot(X, W))

1630.0

## Function taking two matrices

In [16]:
def f(X, W):
    return np.sum(np.dot(X, W))

In [17]:
f(X, W)

1630.0

## Iteration over Numpy Array

In [18]:
copyX = np.zeros_like(X)
itr = np.nditer(X, flags=['multi_index'], op_flags=['writeonly'])
while not itr.finished:
#     itr[0] = it.multi_index[1] - it.multi_index[0]
    print(itr[0], itr.multi_index)
    print("===before==")
    print(X)
    itr[0] += 1
    copyX[itr.multi_index] = itr[0]
    print("===after==")
    print(X)
    itr.iternext()

1.0 (0, 0)
===before==
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
===after==
[[ 2.  2.  3.]
 [ 4.  5.  6.]]
2.0 (0, 1)
===before==
[[ 2.  2.  3.]
 [ 4.  5.  6.]]
===after==
[[ 2.  3.  3.]
 [ 4.  5.  6.]]
3.0 (0, 2)
===before==
[[ 2.  3.  3.]
 [ 4.  5.  6.]]
===after==
[[ 2.  3.  4.]
 [ 4.  5.  6.]]
4.0 (1, 0)
===before==
[[ 2.  3.  4.]
 [ 4.  5.  6.]]
===after==
[[ 2.  3.  4.]
 [ 5.  5.  6.]]
5.0 (1, 1)
===before==
[[ 2.  3.  4.]
 [ 5.  5.  6.]]
===after==
[[ 2.  3.  4.]
 [ 5.  6.  6.]]
6.0 (1, 2)
===before==
[[ 2.  3.  4.]
 [ 5.  6.  6.]]
===after==
[[ 2.  3.  4.]
 [ 5.  6.  7.]]


## Numerical Gradient of Matrices

In [19]:
def numerical_gradient(X, W):
    h = 1e-4
    dX = np.zeros_like(X)
    dW = np.zeros_like(W)
    
    itr = np.nditer(X, flags=['multi_index'], op_flags=['readwrite'])
    while not itr.finished:
        original = itr[0].copy()
        
        itr[0] = original + h
        v1 = f(X, W)
        itr[0] = original - h
        v2 = f(X, W)
        dX[itr.multi_index] = (v1 - v2) / (2 * h)
        
        X[itr.multi_index] = original        
        itr.iternext()

    itr = np.nditer(W, flags=['multi_index'], op_flags=['readwrite'])
    while not itr.finished:
        original = itr[0].copy()
        
        itr[0] = original + h
        v1 = f(X, W)
        itr[0] = original - h
        v2 = f(X, W)
        dW[itr.multi_index] = (v1 - v2) / (2 * h)
        
        itr[0] = original
        itr.iternext()
            
    return dX, dW

## Gradient of Matrix Multiplication

In [20]:
dX, dW = numerical_gradient(X, W)

In [21]:
print('dX')
print(dX)

dX
[[  30.   70.  110.]
 [  30.   70.  110.]]


In [22]:
print('dW')
print(dW)

dW
[[  7.   7.]
 [  9.   9.]
 [ 11.  11.]]


In [23]:
X = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])
W = np.array([
    [10.0, 9.0],
    [8.0, 7.0],
    [6.0, 5.0]
])
f(X, W)
# np.dot(X, W)

299.0

In [24]:
X2 = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])
W2 = np.array([
    [10.0, 9.0],
    [8.0, 7.0],
    [6.0, 5.0]
])
f(X2, W2)

299.0

In [25]:
np.dot(np.ones((2,2)), W.T)

array([[ 19.,  15.,  11.],
       [ 19.,  15.,  11.]])

In [26]:
np.dot(X.T, np.ones((2,2)))

array([[ 5.,  5.],
       [ 7.,  7.],
       [ 9.,  9.]])