In [1]:
import numpy as np
import tensorflow as tf

# 07-05: Efficient Convolution Backward Pass using col2im

Try calculating with NumPy, then check with TensorFlow's autograd

#### 1. Basic 2D Convolution
$(4 \times 4) * (3 \times 3) = (2 \times 2)$

#### 2. Padding
$(4 \times 4) * (3 \times 3) = (4 \times 4)$ where $P=1$

#### 3. Stride
$(7 \times 7) * (3 \times 3) = (3 \times 3)$ where $S=2$

#### 4. Padding and Stride
$(7 \times 7) * (3 \times 3) = (4 \times 4)$ where $P=1, S=2$

#### 5. Channel
$(4 \times 4 \times 3) * (3 \times 3 \times 3) = (2 \times 2)$

#### 6. Channel and bias 
$(4 \times 4 \times 3) * (3 \times 3 \times 3) + (1) = (2 \times 2)$

#### 7. Multiple Filters
$(4 \times 4 \times 3) * (3 \times 3 \times 3 \times 4) = (2 \times 2 \times 4)$

#### 8.Multiple Filters + bias 
$(4 \times 4 \times 3) * (3 \times 3 \times 3 \times 4) + (4)= (2 \times 2 \times 4)$

#### 9. Mini-batch + bias
$(3 \times 4 \times 4 \times 3) * (3 \times 3 \times 3 \times 4) + (4)= (3 \times 2 \times 2 \times 4)$

#### 10. RGB Mini-batch $*$ Multiple Filters with stride and padding
$(3 \times 7 \times 7 \times 3) * (3 \times 3 \times 3 \times 4) + (4)= (3 \times 4 \times 4 \times 4)$ where $P=1, S=2$


In [2]:
def float_sequence(size):
    return np.arange(size, dtype=np.float32)

### 1. Basic Convolution Backward

$(4 \times 4) * (3 \times 3) = (2 \times 2)$

In [5]:
X = float_sequence(4*4).reshape(4,4)
W = 12 - float_sequence(3*3).reshape(3,3)

dY = np.ones((2,2))

print("=== dY ===")     
print(dY)

dX = np.zeros((4,4))
dW = np.zeros((3,3))

for h in range(4-3+1):
    for w in range(4-3+1):
        h_start = h
        h_end   = h_start + 3
        w_start = w
        w_end   = w_start + 3
        
        current_dY = dY[h, w]
        dX[h_start:h_end, w_start:w_end] += current_dY * W
        dW += current_dY * X[h_start:h_end, w_start:w_end]
        
print("=== dX ===")     
print(dX)
        
print("=== dW ===")     
print(dW)

#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X.reshape(1, 4, 4, 1))
    tf_W = tf.Variable(W.reshape(3, 3, 1, 1))
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, 1, 1, 1], padding='VALID')
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW = sess.run(tf_grad)
    print("=== L (tf) ===")     
    print(tf_L_val)
    print("=== dX (tf) ===")     
    print(tf_dX[0, :, :, 0])
    print("=== dW (tf) ===")     
    print(tf_dW[:, :, 0, 0])

print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[0, :, :, 0]))
print("dY: ", np.all(dW == tf_dW[:, :, 0, 0]))

=== dY ===
[[ 1.  1.]
 [ 1.  1.]]
=== dX ===
[[ 12.  23.  21.  10.]
 [ 21.  40.  36.  17.]
 [ 15.  28.  24.  11.]
 [  6.  11.   9.   4.]]
=== dW ===
[[ 10.  14.  18.]
 [ 26.  30.  34.]
 [ 42.  46.  50.]]
=== L (tf) ===
1848.0
=== dX (tf) ===
[[ 12.  23.  21.  10.]
 [ 21.  40.  36.  17.]
 [ 15.  28.  24.  11.]
 [  6.  11.   9.   4.]]
=== dW (tf) ===
[[ 10.  14.  18.]
 [ 26.  30.  34.]
 [ 42.  46.  50.]]
=== Matched? ===
dX:  True
dY:  True


### 2. Convolution with padding

$(4 \times 4) * (3 \times 3) = (4 \times 4)$ where $P=1$

In [6]:
X_org = float_sequence(4*4).reshape(4,4)
P = 1
X = np.pad(X_org, ((P, P), (P, P)), 'constant')
W = 12 - float_sequence(3*3).reshape(3,3)

dY = np.ones((4,4))

dX = np.zeros((6,6))
dW = np.zeros((3,3))

for h in range(4):
    for w in range(4):
        h_start = h
        h_end   = h_start + 3
        w_start = w
        w_end   = w_start + 3
        
        current_dY = dY[h, w]
        dX[h_start:h_end, w_start:w_end] += current_dY * W
        dW += current_dY * X[h_start:h_end, w_start:w_end]

dX = dX[P:-P, P:-P] # unpad
print("=== dX ===")
print(dX)
        
print("=== dW ===")     
print(dW)

#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X_org.reshape(1, 4, 4, 1))
    tf_W = tf.Variable(W.reshape(3, 3, 1, 1))
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, 1, 1, 1], padding='SAME')
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW = sess.run(tf_grad)
    print("=== dX (tf) ===")     
    print(tf_dX[0, :, :, 0])
    print("=== dW (tf) ===")     
    print(tf_dW[:, :, 0, 0])

print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[0, :, :, 0]))
print("dY: ", np.all(dW == tf_dW[:, :, 0, 0]))

=== dX ===
[[ 40.  57.  57.  36.]
 [ 51.  72.  72.  45.]
 [ 51.  72.  72.  45.]
 [ 28.  39.  39.  24.]]
=== dW ===
[[  45.   66.   54.]
 [  84.  120.   96.]
 [  81.  114.   90.]]
=== dX (tf) ===
[[ 40.  57.  57.  36.]
 [ 51.  72.  72.  45.]
 [ 51.  72.  72.  45.]
 [ 28.  39.  39.  24.]]
=== dW (tf) ===
[[  45.   66.   54.]
 [  84.  120.   96.]
 [  81.  114.   90.]]
=== Matched? ===
dX:  True
dY:  True


### 3. Convolution with Stride

$(7 \times 7) * (3 \times 3) = (3 \times 3)$ where $S=2$

In [7]:
X = float_sequence(7*7).reshape(7,7)
W = 12 - float_sequence(3*3).reshape(3,3)
S = 2

dY = np.ones((3,3))

dX = np.zeros((7,7))
dW = np.zeros((3,3))

for h in range(3):
    for w in range(3):
        h_start = h * S
        h_end   = h_start + 3
        w_start = w * S
        w_end   = w_start + 3
        
        current_dY = dY[h, w]
        dX[h_start:h_end, w_start:w_end] += current_dY * W
        dW += current_dY * X[h_start:h_end, w_start:w_end]
        
print("=== dX ===")     
print(dX)
        
print("=== dW ===")     
print(dW)

#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X.reshape(1, 7, 7, 1))
    tf_W = tf.Variable(W.reshape(3, 3, 1, 1))
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, S, S, 1], padding='VALID')
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW = sess.run(tf_grad)
    print("=== L (tf) ===")     
    print(tf_L_val)
    print("=== dX (tf) ===")     
    print(tf_dX[0, :, :, 0])
    print("=== dW (tf) ===")     
    print(tf_dW[:, :, 0, 0])

print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[0, :, :, 0]))
print("dY: ", np.all(dW == tf_dW[:, :, 0, 0]))

=== dX ===
[[ 12.  11.  22.  11.  22.  11.  10.]
 [  9.   8.  16.   8.  16.   8.   7.]
 [ 18.  16.  32.  16.  32.  16.  14.]
 [  9.   8.  16.   8.  16.   8.   7.]
 [ 18.  16.  32.  16.  32.  16.  14.]
 [  9.   8.  16.   8.  16.   8.   7.]
 [  6.   5.  10.   5.  10.   5.   4.]]
=== dW ===
[[ 144.  153.  162.]
 [ 207.  216.  225.]
 [ 270.  279.  288.]]
=== L (tf) ===
14364.0
=== dX (tf) ===
[[ 12.  11.  22.  11.  22.  11.  10.]
 [  9.   8.  16.   8.  16.   8.   7.]
 [ 18.  16.  32.  16.  32.  16.  14.]
 [  9.   8.  16.   8.  16.   8.   7.]
 [ 18.  16.  32.  16.  32.  16.  14.]
 [  9.   8.  16.   8.  16.   8.   7.]
 [  6.   5.  10.   5.  10.   5.   4.]]
=== dW (tf) ===
[[ 144.  153.  162.]
 [ 207.  216.  225.]
 [ 270.  279.  288.]]
=== Matched? ===
dX:  True
dY:  True


### 4. Padding and Stride

$(7 \times 7) * (3 \times 3) = (4 \times 4)$ where $P=1, S=2$

In [8]:
P = 1
S = 2
X_org = float_sequence(7*7).reshape(7,7)
X = np.pad(X_org, ((P, P), (P, P)), 'constant')
W = 12 - float_sequence(3*3).reshape(3,3)

# print("=== X ===")
# print(X)
# print("=== W ===")
# print(W)

dY = np.ones((4,4))

dX = np.zeros((9,9))
dW = np.zeros((3,3))

for h in range(4):
    for w in range(4):
        h_start = h * S
        h_end   = h_start + 3
        w_start = w * S
        w_end   = w_start + 3
        
        current_dY = dY[h, w]
        dX[h_start:h_end, w_start:w_end] += current_dY * W
        dW += current_dY * X[h_start:h_end, w_start:w_end]

dX = dX[P:-P, P:-P] # unpad
print("=== dX ===")     
print(dX)
        
print("=== dW ===")     
print(dW)

#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X_org.reshape(1, 7, 7, 1))
    tf_W = tf.Variable(W.reshape(3, 3, 1, 1))
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, S, S, 1], padding='SAME')
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW = sess.run(tf_grad)
    print("=== L (tf) ===")     
    print(tf_L_val)
    print("=== dX (tf) ===")     
    print(tf_dX[0, :, :, 0])
    print("=== dW (tf) ===")     
    print(tf_dW[:, :, 0, 0])

# print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[0, :, :, 0]))
print("dY: ", np.all(dW == tf_dW[:, :, 0, 0]))

=== dX ===
[[  8.  16.   8.  16.   8.  16.   8.]
 [ 16.  32.  16.  32.  16.  32.  16.]
 [  8.  16.   8.  16.   8.  16.   8.]
 [ 16.  32.  16.  32.  16.  32.  16.]
 [  8.  16.   8.  16.   8.  16.   8.]
 [ 16.  32.  16.  32.  16.  32.  16.]
 [  8.  16.   8.  16.   8.  16.   8.]]
=== dW ===
[[ 216.  288.  216.]
 [ 288.  384.  288.]
 [ 216.  288.  216.]]
=== L (tf) ===
19200.0
=== dX (tf) ===
[[  8.  16.   8.  16.   8.  16.   8.]
 [ 16.  32.  16.  32.  16.  32.  16.]
 [  8.  16.   8.  16.   8.  16.   8.]
 [ 16.  32.  16.  32.  16.  32.  16.]
 [  8.  16.   8.  16.   8.  16.   8.]
 [ 16.  32.  16.  32.  16.  32.  16.]
 [  8.  16.   8.  16.   8.  16.   8.]]
=== dW (tf) ===
[[ 216.  288.  216.]
 [ 288.  384.  288.]
 [ 216.  288.  216.]]
dX:  True
dY:  True


### 5. Channel

$(4 \times 4 \times 3) * (3 \times 3 \times 3) = (2 \times 2)$

In [9]:
X = float_sequence(4*4*3).reshape(4,4,3)
W = 30 - float_sequence(3*3*3).reshape(3,3,3)
# print("=== X ===")
# print(X.transpose(2, 0, 1))
# print("=== W ===")
# print(W.transpose(2, 0, 1))

dY = np.ones((2,2))

# print("=== dY ===")     
# print(dY)

dX = np.zeros((4,4,3))
dW = np.zeros((3,3,3))

for h in range(4-3+1):
    for w in range(4-3+1):
        h_start = h
        h_end   = h_start + 3
        w_start = w
        w_end   = w_start + 3
        
        current_dY = dY[h, w]
        dX[h_start:h_end, w_start:w_end, :] += current_dY * W
        dW += current_dY * X[h_start:h_end, w_start:w_end, :]
        
# print("=== dX ===")     
# print(dX)
        
# print("=== dW ===")     
# print(dW)

#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X.reshape(1, 4, 4, 3))
    tf_W = tf.Variable(W.reshape(3, 3, 3, 1))
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, 1, 1, 1], padding='VALID')
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW = sess.run(tf_grad)
    print("=== L (tf) ===")     
    print(tf_L_val)
    print("=== dX (tf) ===")     
    print(tf_dX[0, :, :, :])
#     print("=== dW (tf) ===")     
#     print(tf_dW[:, :, :, 0])

print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[0, :, :, :]))
print("dY: ", np.all(dW == tf_dW[:, :, :, 0]))

=== L (tf) ===
34650.0
=== dX (tf) ===
[[[ 30.  29.  28.]
  [ 57.  55.  53.]
  [ 51.  49.  47.]
  [ 24.  23.  22.]]

 [[ 51.  49.  47.]
  [ 96.  92.  88.]
  [ 84.  80.  76.]
  [ 39.  37.  35.]]

 [[ 33.  31.  29.]
  [ 60.  56.  52.]
  [ 48.  44.  40.]
  [ 21.  19.  17.]]

 [[ 12.  11.  10.]
  [ 21.  19.  17.]
  [ 15.  13.  11.]
  [  6.   5.   4.]]]
=== Matched? ===
dX:  True
dY:  True


### 6. Channel and bias 

$(4 \times 4 \times 3) * (3 \times 3 \times 3) + (1) = (2 \times 2)$

In [11]:
X = float_sequence(4*4*3).reshape(4,4,3)
W = 30 - float_sequence(3*3*3).reshape(3,3,3)
b = np.array([10], dtype=np.float32)
# print("=== X ===")
# print(X.transpose(2, 0, 1))
# print("=== W ===")
# print(W.transpose(2, 0, 1))

dY = np.ones((2,2))

# print("=== dY ===")     
# print(dY)


db = np.sum(dY)
dX = np.zeros((4,4,3))
dW = np.zeros((3,3,3))

for h in range(4-3+1):
    for w in range(4-3+1):
        h_start = h
        h_end   = h_start + 3
        w_start = w
        w_end   = w_start + 3
        
        current_dY = dY[h, w]
        dX[h_start:h_end, w_start:w_end, :] += current_dY * W
        dW += current_dY * X[h_start:h_end, w_start:w_end, :]
        
# print("=== dX ===")     
# print(dX)
        
# print("=== dW ===")     
# print(dW)

print("=== db ===")     
print(db)

#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X.reshape(1, 4, 4, 3))
    tf_W = tf.Variable(W.reshape(3, 3, 3, 1))
    tf_b = tf.constant(b)
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, 1, 1, 1], padding='VALID') + tf_b
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W, tf_b])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW, tf_db = sess.run(tf_grad)
#     print("=== L (tf) ===")     
#     print(tf_L_val)
#     print("=== dX (tf) ===")     
#     print(tf_dX[0, :, :, :])
#     print("=== dW (tf) ===")     
#     print(tf_dW[:, :, :, 0])
    print("=== db (tf) ===")     
    print(tf_db[0])

print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[0, :, :, :]))
print("dY: ", np.all(dW == tf_dW[:, :, :, 0]))
print("db: ", np.all(db == tf_db[0]))

=== db ===
4.0
=== db (tf) ===
4.0
=== Matched? ===
dX:  True
dY:  True
db:  True


### 7. Multiple Filters

$(4 \times 4 \times 3) * (3 \times 3 \times 3 \times 4) = (2 \times 2 \times 4)$

In [12]:
X = float_sequence(4*4*3).reshape(4,4,3)
W = 120 - float_sequence(3*3*3*4).reshape(3,3,3,4)


dY = np.ones((2,2,4))

dX = np.zeros((4,4,3))
dW = np.zeros((3,3,3,4))

for h in range(4-3+1):
    for w in range(4-3+1):
        h_start = h
        h_end   = h_start + 3
        w_start = w
        w_end   = w_start + 3
        
        for c_out in range(4):
            current_dY = dY[h, w, c_out]
            dX[h_start:h_end, w_start:w_end, :] += current_dY * W[:, :, :, c_out]
            dW[:, :, :, c_out] += current_dY * X[h_start:h_end, w_start:w_end, :]
        
# print("=== dX ===")     
# print(dX)
        
# print("=== dW ===")     
# print(dW)

#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X.reshape(1, 4, 4, 3))
    tf_W = tf.Variable(W.reshape(3, 3, 3, 4))
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, 1, 1, 1], padding='VALID')
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW = sess.run(tf_grad)
#     print("=== L (tf) ===")     
#     print(tf_L_val)
#     print("=== dX (tf) ===")     
#     print(tf_dX[0, :, :, :])
#     print("=== dW (tf) ===")     
#     print(tf_dW[:, :, :, :])

print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[0, :, :, :]))
print("dY: ", np.all(dW == tf_dW[:, :, :, :]))

=== Matched? ===
dX:  True
dY:  True


### 8. Multiple Filters + bias 

$(4 \times 4 \times 3) * (3 \times 3 \times 3 \times 4) + (4)= (2 \times 2 \times 4)$

In [13]:
X = float_sequence(4*4*3).reshape(4,4,3)
W = 120 - float_sequence(3*3*3*4).reshape(3,3,3,4)
b = np.array([10, 100, 1000, 10000], dtype=np.float32)

dY = np.ones((2,2,4))

db = np.sum(dY, axis=(0,1))
dX = np.zeros((4,4,3))
dW = np.zeros((3,3,3,4))

for h in range(4-3+1):
    for w in range(4-3+1):
        h_start = h
        h_end   = h_start + 3
        w_start = w
        w_end   = w_start + 3
        
        for c_out in range(4):
            current_dY = dY[h, w, c_out]
            dX[h_start:h_end, w_start:w_end, :] += current_dY * W[:, :, :, c_out]
            dW[:, :, :, c_out] += current_dY * X[h_start:h_end, w_start:w_end, :]
        
# print("=== dX ===")     
# print(dX)
        
# print("=== dW ===")     
# print(dW)

print("=== db ===")     
print(db)

#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X.reshape(1, 4, 4, 3))
    tf_W = tf.Variable(W.reshape(3, 3, 3, 4))
    tf_b = tf.constant(b)
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, 1, 1, 1], padding='VALID') + tf_b
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W, tf_b])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW, tf_db = sess.run(tf_grad)
#     print("=== L (tf) ===")     
#     print(tf_L_val)
#     print("=== dX (tf) ===")     
#     print(tf_dX[0, :, :, :])
#     print("=== dW (tf) ===")     
#     print(tf_dW[:, :, :, :])
    print("=== db (tf) ===")     
    print(tf_db)


print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[0, :, :, :]))
print("dY: ", np.all(dW == tf_dW[:, :, :, :]))
print("db: ", np.all(db == tf_db))

=== db ===
[ 4.  4.  4.  4.]
=== db (tf) ===
[ 4.  4.  4.  4.]
=== Matched? ===
dX:  True
dY:  True
db:  True


### 9. Mini-batch + bias

$(3 \times 4 \times 4 \times 3) * (3 \times 3 \times 3 \times 4) + (4)= (3 \times 2 \times 2 \times 4)$

In [14]:
X = float_sequence(3*4*4*3).reshape(3,4,4,3)
W = 120 - float_sequence(3*3*3*4).reshape(3,3,3,4)
b = np.array([10, 100, 1000, 10000], dtype=np.float32)

dY = np.ones((3,2,2,4))

db = np.sum(dY, axis=(0,1,2))
dX = np.zeros((3,4,4,3))
dW = np.zeros((3,3,3,4))

for h in range(4-3+1):
    for w in range(4-3+1):
        h_start = h
        h_end   = h_start + 3
        w_start = w
        w_end   = w_start + 3
        
        for n_batch in range(3):
            for c_out in range(4):
                current_dY = dY[n_batch, h, w, c_out]
                dX[n_batch, h_start:h_end, w_start:w_end, :] += current_dY * W[:, :, :, c_out]
                dW[:, :, :, c_out] += current_dY * X[n_batch, h_start:h_end, w_start:w_end, :]
        
# print("=== dX ===")     
# print(dX)
        
# print("=== dW ===")     
# print(dW)

# print("=== db ===")     
# print(db)

#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X.reshape(3, 4, 4, 3))
    tf_W = tf.Variable(W.reshape(3, 3, 3, 4))
    tf_b = tf.constant(b)
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, 1, 1, 1], padding='VALID') + tf_b
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W, tf_b])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW, tf_db = sess.run(tf_grad)
#     print("=== L (tf) ===")     
#     print(tf_L_val)
#     print("=== dX (tf) ===")     
#     print(tf_dX[0, :, :, :])
#     print("=== dW (tf) ===")     
#     print(tf_dW[:, :, :, :])
#     print("=== db (tf) ===")     
#     print(tf_db)


print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[:, :, :, :]))
print("dY: ", np.all(dW == tf_dW[:, :, :, :]))
print("db: ", np.all(db == tf_db))

=== Matched? ===
dX:  True
dY:  True
db:  True


#### 10. RGB Mini-batch $*$ Multiple Filters with stride and padding
$(3 \times 7 \times 7 \times 3) * (3 \times 3 \times 3 \times 4) + (4)= (3 \times 4 \times 4 \times 4)$ where $P=1, S=2$

In [15]:
P = 1
S = 2
X_org = float_sequence(3*7*7*3).reshape(3,7,7,3)
X = np.pad(X_org, ((0, 0), (P, P), (P, P), (0, 0)), 'constant')
W = 120 - float_sequence(3*3*3*4).reshape(3,3,3,4)
b = np.array([10, 100, 1000, 10000], dtype=np.float32)

dY = np.ones((3,4,4,4))

db = np.sum(dY, axis=(0,1,2))
dX = np.zeros((3,9,9,3))
dW = np.zeros((3,3,3,4))

for h in range(4):
    for w in range(4):
        h_start = h * S
        h_end   = h_start + 3
        w_start = w * S
        w_end   = w_start + 3
        
        for n_batch in range(3):
            for c_out in range(4):
                current_dY = dY[n_batch, h, w, c_out]
                dX[n_batch, h_start:h_end, w_start:w_end, :] += current_dY * W[:, :, :, c_out]
                dW[:, :, :, c_out] += current_dY * X[n_batch, h_start:h_end, w_start:w_end, :]

dX = dX[:, P:-P, P:-P, :] # unpad
# print("=== dX ===")     
# print(dX)
        
# print("=== dW ===")     
# print(dW)

# print("=== db ===")     
# print(db)


#================== tf ==================
with tf.Session() as sess:
    tf_X = tf.constant(X_org.reshape(3, 7, 7, 3))
    tf_W = tf.Variable(W.reshape(3, 3, 3, 4))
    tf_b = tf.constant(b)
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, S, S, 1], padding='SAME') + tf_b
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W, tf_b])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW, tf_db = sess.run(tf_grad)
#     print("=== L (tf) ===")     
#     print(tf_L_val)
#     print("=== dX (tf) ===")     
#     print(tf_dX[0, :, :, :])
#     print("=== dW (tf) ===")     
#     print(tf_dW[:, :, :, :])
#     print("=== db (tf) ===")     
#     print(tf_db)


print("=== Matched? ===")    
print("dX: ", np.all(dX == tf_dX[:, :, :, :]))
print("dY: ", np.all(dW == tf_dW[:, :, :, :]))
print("db: ", np.all(db == tf_db))

=== Matched? ===
dX:  True
dY:  True
db:  True


# Generalized naive convolution backward

In [17]:
def conv_naive_backward(dY, X, W, b, P=0, S=1):
    N_batch, H_in, W_in, C_in = X.shape
    H_filter, W_filter, _, C_out = W.shape
    _, H_out, W_out, _ = dY.shape
    
    if P > 0:
        X = np.pad(X, ((0, 0), (P, P), (P, P), (0, 0)), 'constant')
    
    db = np.sum(dY, axis=(0,1,2))
    dX = np.zeros((N_batch, H_in+2*P, W_in+2*P, C_in))
    dW = np.zeros_like(W)

    for w in range(W_out):
        for h in range(H_out):
            h_start = h * S
            h_end   = h_start + H_filter
            w_start = w * S
            w_end   = w_start + W_filter

            for n_batch in range(N_batch):
                for c_out in range(C_out):
                    current_dY = dY[n_batch, h, w, c_out]
                    dX[n_batch, h_start:h_end, w_start:w_end, :] += current_dY * W[:, :, :, c_out]
                    dW[:, :, :, c_out] += current_dY * X[n_batch, h_start:h_end, w_start:w_end, :]

    dX = dX[:, P:-P, P:-P, :]
    
    return (dX, dW, db)

In [18]:
P = 1
S = 2
X = np.random.randn(3, 7, 7, 3).astype(np.float32)
W = np.random.randn(3,3,3,4).astype(np.float32)
b = np.random.randn(4).astype(np.float32)

dY = np.ones((3,4,4,4))
dX, dW, db = conv_naive_backward(dY, X, W, b, P, S)

with tf.Session() as sess:
    tf_X = tf.constant(X)
    tf_W = tf.Variable(W)
    tf_b = tf.constant(b)
    tf_Y = tf.nn.conv2d(tf_X, tf_W, strides=[1, S, S, 1], padding='SAME') + tf_b
    tf_L = tf.reduce_sum(tf_Y)
    tf_grad = tf.gradients(tf_L, [tf_X, tf_W, tf_b])
    
    sess.run(tf.global_variables_initializer())
    tf_L_val = sess.run(tf_L)
    tf_dX, tf_dW, tf_db = sess.run(tf_grad)
        
check_dX = np.linalg.norm(dX - tf_dX) / (np.linalg.norm(dX) + np.linalg.norm(tf_dX))
check_dW = np.linalg.norm(dW - tf_dW) / (np.linalg.norm(dW) + np.linalg.norm(tf_dW))
check_db = np.linalg.norm(db - tf_db) / (np.linalg.norm(db) + np.linalg.norm(tf_db))

print("=== Matched? ===")    
print("dX: ", check_dX < 1e-7, check_dX)
print("dW: ", check_dW < 1e-7, check_dW)
print("db: ", check_db < 1e-7, check_db)

=== Matched? ===
dX:  True 2.14135281647e-08
dW:  True 5.97622e-08
db:  True 0.0
