In [1]:
import numpy as np
import tensorflow as tf

In [65]:
X = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=tf.float32)
X2 = tf.reshape(X, [-1, 3, 3, 1])

W = np.array([
    [[[1.0, 5.0]], [[2.0, 6.0]]],
    [[[2.0, 7.0]], [[1.0, 8.0]]]
])
W2 = tf.constant(W, dtype=tf.float32)

conv = tf.nn.conv2d(X2, W2, strides=[1, 1, 1, 1], padding='VALID')

In [68]:
with tf.Session() as sess:
    out = sess.run([X2, W2, conv])

    
    print("--X2.shape--")
    print(X2.shape)
    print("X2")
    print(out[0][0, :, :, 0])
    print('')
    
    print("--W2.shape--")
    print(W2.shape)
    print("W2 first")
    print(out[1][:, :, 0, 0])
    print("W2 second")
    print(out[1][:, :, 0, 1])
    print('')
    
    print("--Convolution--")
    print(out[2].shape)
    print("First filter")
    print(out[2][0, :, :, 0])
    
    print("Second filter")
    print(out[2][0, :, :, 1])

--X2.shape--
(1, 3, 3, 1)
X2
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]

--W2.shape--
(2, 2, 1, 2)
W2 first
[[ 1.  2.]
 [ 2.  1.]]
W2 second
[[ 5.  6.]
 [ 7.  8.]]

--Convolution--
(1, 2, 2, 2)
First filter
[[ 18.  24.]
 [ 36.  42.]]
Second filter
[[  85.  111.]
 [ 163.  189.]]


[tf.nn.conv2d](https://www.tensorflow.org/api_docs/python/tf/nn/conv2d)